# Generated by Django 3.0.7 on 2020-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
